### ISSUE TITLE
Algebra command

### ISSUE THREAD

**Issue by Rijkaron** [HeyYo-Discord/suggesties#1]
Het zou leuk zijn als er naast het .calc command ook een mogelijkheid was voor het oplossen van algebraische vergelijkingen. Dat zou in het .calc command kunnen of in een nieuw command zoals .algebra oid.
Bij de input `.algebra 2x+4=18` zou bijvoorbeeld er `x = 7` uit moeten komen.

**Comment by Jazzkuh** [comment]
Je kan het ook gwn toevoegen aan .calc

**Comment by stijnvdkolk** [comment]
Nee, nieuw commando

**Comment by Jazzkuh** [comment]
Nee
.calc --algebra expression

**Comment by stijnvdkolk** [comment]
Ja

**Comment by stijnvdkolk** [comment]
Doe het graag voor je!

**Comment by Jazzkuh** [comment]
patat

**Comment by stijnvdkolk** [comment]
Blijf eens van mijn comments af

**Comment by Jazzkuh** [comment]
ps, when

**Comment by stijnvdkolk** [comment]
Binnenkort?
